[package]
name = "rusty_xml-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "UTF-8 well-formed XML parser (libxml2 parser.h semantics)"
keywords.workspace = true
categories.workspace = true

[dependencies]
rusty_xml-sax = { workspace = true }
rusty_xml-tree = { workspace = true }

[lints]
workspace = true
