[package]
name = "rusty_xml-writer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "xmlsave + xmlTextWriter for rusty_xml"
keywords.workspace = true
categories.workspace = true

[dependencies]
rusty_xml-tree = { workspace = true }

[lints]
workspace = true
